### ISSUE TITLE
Codewars link

### ISSUE THREAD

**Issue by msroji** [dvid-d/Programming-Challenges#2]
https://github.com/dvid-d/Programming-Challenges/blob/d97ca703241d64644b83ed63e5a5b35180e79b4b/Brampton%20Manor%20Academy/Programming%20Challenge%201/codewards_challenge.py#L1

Add a comment which gives the hyperlink to the codewars challenge as your first line of code. This would help in referring back to the question later on

**Comment by dvid-d** [comment]
Below is the link with the link as the first line of code. 

https://github.com/dvid-d/Programming-Challenges/blob/main/Codewars/codewards_challenge.py
